version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: image
    restart: always
    depends_on:
    - ollama 
    ports:
    - "5000"
    networks:
      - ollama-docker

  ollama:
    image: ollama/ollama
    ports:
    - "11434:11434"
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    networks:
      - ollama-docker

  nginx:
    image: nginx:1.24.0
    restart: unless-stopped
    depends_on:
    - api
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./certbot/conf:/etc/letsencrypt
    - ./certbot/www:/var/www/certbot
    networks:
      - ollama-docker

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsecnrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email azamatdzabaev310@gmail.com -d leetbot.ru --agree-tos
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false
