version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    image: image:${IMAGE_VERSION:-latest}
    restart: always
    ports:
    - "5000"

  nginx:
    image: nginx:1.24.0
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
    - api
    ports:
    - "80:80"
